name: Check Must Reviewers Test

on:
  pull_request:
    types: [opened,synchronize,reopened] 
  
jobs:
  must-reviewer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Reading MUSTREVIEWERS file
        id: read_mustReviewers
        uses: andstor/file-reader-action@v1
        with:
          path: ".github/MUSTREVIEWERS.txt"
        
      - name: Set MustReviewers Output
        id: set_mustReviewers_output
        run: | 
          echo ":: set-output name=contents ${{steps.read_mustReviewers.outputs.contents}}" 
      
      - name: File contents
        run: echo "${{steps.read_mustReviewers.outputs.contents}}" 

      - name: MUSTREVIEWERS CHECK
        uses: BetssonGroup/sb-b2b-must-reviewer-check-workflow/tree/feature/SBB2B-7979-Implement-must-review-process@1.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          must-reviewers: ${{steps.read_mustReviewers.outputs.contents}}
 
              
      
