name: Check Must Reviewers Test

on:
  push: 
  
jobs:
  must-reviewer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Reading MUSTREVIEWERS file
        id: read_mustReviewers
        run: |
          mustReviewers = ${cat .github/MUSTREVIEWERS.txt}
          echo "Usernames from file: $usernames"
          echo "::set-output name=usernames::$usernames"

      # - name: MUSTREVIEWERS CHECK
      #   uses: BetssonGroup/sb-b2b-must-reviewer-check-workflow@1.0.0
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     must-reviewers: ${{steps.read_mustReviewers.outputs.usernames}}
 
              
      
