name: Update Release branch with master

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.matrix.outputs.value }}
    steps:
        - name: listPullRequests
          uses: buildsville/list-pull-requests@v1
          id: list
          with:
            token: ${{secrets.GITHUB_TOKEN}}
            labels: '[""]'
            skip_hour: '0'
        - name: output
          run: echo '${{ steps.list.outputs.pulls }}'
  sync-release-pr-branches:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
        matrix:
          value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: merge
        uses: mtanzi/action-automerge@v1
        if: ${{ success() && startsWith(steps.extract_branch.outputs.branch, 'release' ) || startsWith(steps.extract_branch.outputs.branch, 'integration' )}}
        id: merge
        with:
          github_token: ${{ github.token }}
          source: '${{ steps.extract_branch.outputs.branch }}'
          target: '${{ steps.extract_branch.outputs.branch }}'