name: Update Release branch with master

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.matrix.outputs.value }}
    steps:
        - id: matrix
          run: |
            ```
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/adsz01/editor-config-poc/pulls
            ```
        - run: |
            echo "${{ steps.matrix.outputs.value }}"
  sync-release-pr-branches:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
        matrix:
          value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: merge
        uses: mtanzi/action-automerge@v1
        if: ${{ success() && startsWith(steps.extract_branch.outputs.branch, 'release' ) || startsWith(steps.extract_branch.outputs.branch, 'integration' )}}
        id: merge
        with:
          github_token: ${{ github.token }}
          source: '${{ steps.extract_branch.outputs.branch }}'
          target: '${{ steps.extract_branch.outputs.branch }}'